name = "give-your-point"
compatibility_date = "2026-01-28"

# On définit ici le dossier que Wrangler doit surveiller
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "give-your-point-eu"
database_id = "11098dce-acd8-4bf9-ad54-c74f57e5bf04"